services:
  - type: web
    name: recruitment-backend
    runtime: php
    region: oregon
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y unzip
      composer install --no-dev --optimize-autoloader
      php artisan config:clear
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host=0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: CACHE_STORE
        value: redis
      - key: QUEUE_CONNECTION
        value: database
      - key: MAIL_MAILER
        value: smtp
